# Generated by Django 5.1 on 2025-09-02 13:28

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='institution_name', unique=True),
        ),
    ]
