name: CI de Django

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout do Código
      uses: actions/checkout@v2
      
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12' 
        
    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage # Instala a biblioteca para o relatório de cobertura.
        
    - name: Executar Testes do Django com Cobertura
      run: coverage run manage.py test
        
    - name: Gerar Relatório de Cobertura
      run: coverage xml
      
    - name: Publicar Relatório de Cobertura
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.xml