# .github/workflows/build-and-test.yml

name: Build, Test and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage # Garante que a ferramenta de cobertura está instalada

      - name: Executar testes e Gerar Relatório de Cobertura
        run: |
          # 1. Roda os testes monitorando o código
          coverage run manage.py test
          
          # 2. Gera o relatório no formato XML que o SonarQube entende
          coverage xml

      - name: Executar Análise do SonarQube
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Fornecido pelo GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}      # O token que você configurou
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # A URL que você configurou